//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Asiakkaat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiakkaat()
        {
            this.Tilaukset = new HashSet<Tilaukset>();
        }

        public int AsiakasID { get; set; }
        [Display(Name = "Asiakas")]
        public string Nimi { get; set; }
        public string Osoite { get; set; }
        [DataType(DataType.PostalCode)]
        public string Postinumero { get; set; }
        public Nullable<int> Vastuumyyja { get; set; }
        [Range(1, 999999)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Nullable<decimal> Luottoraja { get; set; }
        [DataType(DataType.Url)]
        [Display(Name = "Www-sivut")]
        public string www_sivut { get; set; }

        public string VastuumyyjaNimi 
        {
            get { return $"{this.Henkilot.Etunimi} {this.Henkilot.Sukunimi}"; }
        }
        public string PostiTmp 
        {
            get { return $"{this.Postitoimipaikat.Postinumero} {this.Postitoimipaikat.Postitoimipaikka}"; }
        }
        public virtual Henkilot Henkilot { get; set; }
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilaukset> Tilaukset { get; set; }
    }
}
