//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kayttajat
    {
        public int KayttajaId { get; set; }
        [Display(Name = "Käyttäjänimi")]
        [Required]
        public string KayttajaNimi { get; set; }
        [Display(Name = "Salasana")]
        [Required]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }
        public int Rooli { get; set; } = 1;
        public string KirjautumisVirheViesti { get; set; }

        public virtual Roolit Roolit { get; set; }
    }
}
