# Generated by Django 3.2.4 on 2021-07-10 14:36

from django.conf import settings
from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcomment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippetcomment',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(snippets.models.get_sentinel_user), related_name='snippetcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippetpost',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
