# Generated by Django 3.2.4 on 2021-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20210710_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcomment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippetpost',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
