# Generated by Django 3.2.4 on 2021-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210710_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcomment',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippetpost',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
