# Generated by Django 3.2.4 on 2021-07-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20210714_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippetcomment',
            options={'ordering': ['-created']},
        ),
    ]
