# Generated by Django 3.2.4 on 2021-07-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippetcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippetcomment',
            options={'ordering': ['created']},
        ),
    ]
